name: R-CMD-check  # Workflow Name

on: [push, pull_request]  # Runs on every push or pull request

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest  # Use the latest Ubuntu server
    name: Run R CMD check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Install BiocManager
        run: Rscript -e 'install.packages("BiocManager", repos="https://cloud.r-project.org")'

      - name: Install phyloseq manually
        run: Rscript -e 'BiocManager::install("phyloseq", ask=FALSE, update=TRUE)'

      - name: Install remotes package
        run: Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'

      - name: Install rcmdcheck manually
        run: Rscript -e 'remotes::install_cran("rcmdcheck", repos="https://cloud.r-project.org")'

      - name: Install package dependencies
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Verify phyloseq installation
        run: Rscript -e 'if (!requireNamespace("phyloseq", quietly = TRUE)) stop("phyloseq is still missing!")'

      - name: Run R CMD check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")'

      - name: Install testthat
        run: Rscript -e 'install.packages("testthat", repos="https://cloud.r-project.org")'
      - name: Install dependencies
        run: |
          install.packages("BiocManager")
          BiocManager::install("phyloseq")
          install.packages(c("TMB", "Matrix", "gllvm", "rcmdcheck", "testthat"))

      - name: Upload Check Results
        uses: actions/upload-artifact@v4
        with:
          name: r-cmd-check-results
          path: check
          if-no-files-found: ignore

