name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    name: Run R CMD check

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}

    env:
      RSPM: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes        

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: "https://inla.r-inla-download.org/R/testing"

      - name: Install system dependencies on Linux (GL)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libglu1-mesa-dev

      - name: Install system dependencies on MacOS (X11, gdal)
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          brew install pkg-config
          brew install proj@9
          brew install gdal

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
             rcmdcheck  
             
      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        with:
          args: 'c("--no-manual", "--as-cran")'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Install required R packages (CRAN + Bioconductor)
        run: |
          install.packages("BiocManager", repos = "https://cloud.r-project.org")
          BiocManager::install("phyloseq", ask = FALSE, update = TRUE)
          install.packages(c("TMB", "Matrix", "gllvm", "rcmdcheck", "testthat"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Verify that phyloseq is installed
        run: |
          if (!requireNamespace("phyloseq", quietly = TRUE)) {
            stop("❌ phyloseq did not install properly!")
          } else {
            message("✅ phyloseq installed successfully.")
          }
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash


      - name: Upload check results
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check
          if-no-files-found: ignore
