name: R-CMD-check  # Name of the workflow

on: [push, pull_request]  # Runs on every push or pull request

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest  # Runs on latest Ubuntu server
    name: Run R CMD check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes"); remotes::install_cran("rcmdcheck")'


      - name: Install package dependencies
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run R CMD check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")'

      - name: Upload Check Results
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          path: check
