name: R-CMD-check  # Workflow Name

on: [push, pull_request]  # Runs on every push or pull request

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest  # Use the latest Ubuntu server
    name: Run R CMD check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")'

      - name: Verify rcmdcheck installation
        run: Rscript -e 'if (!requireNamespace("rcmdcheck", quietly = TRUE)) { install.packages("rcmdcheck", repos = "https://cloud.r-project.org") }'

      - name: Run R CMD check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")'

      - name: Upload Check Results
        uses: actions/upload-artifact@v4
        with:
          name: r-cmd-check-results
          path: check
          if-no-files-found: ignore
