name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    name: Run R CMD check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Install required R packages (CRAN + Bioconductor)
        run: |
          install.packages("BiocManager", repos = "https://cloud.r-project.org")
          BiocManager::install("phyloseq", ask = FALSE, update = TRUE)
          install.packages(c("TMB", "Matrix", "gllvm", "rcmdcheck", "testthat"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Verify that phyloseq is installed
        run: |
          if (!requireNamespace("phyloseq", quietly = TRUE)) {
            stop("❌ phyloseq did not install properly!")
          } else {
            message("✅ phyloseq installed successfully.")
          }
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check
          if-no-files-found: ignore
