name: test-coverage

on: [push, pull_request]

jobs:
  test-coverage:
    runs-on: ${{ matrix.config.os }}
    name: Test Coverage on ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      R_KEEP_PKG_SOURCE: yes        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
            covr
            rcmdcheck
            BiocManager

      - name: Install Bioconductor packages
        run: |
          if (!requireNamespace("phyloseq", quietly = TRUE)) {
            BiocManager::install("phyloseq", ask = FALSE, update = TRUE)
          }
        shell: Rscript {0}

      - name: Install the package
        run: R CMD INSTALL .
        shell: bash

      - name: Run test coverage and report to Codecov
        run: covr::codecov()
        shell: Rscript {0}

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results-${{ github.run_number }}
          path: .  # or specify the coverage file directory if saved
